/**
 * Generated by `npm run pin-models`. Do not edit by hand.
 *
 * The true size and SHA-256 of each catalogue variant's file, at the revision
 * the catalogue names. Kept apart from the catalogue itself because these are
 * facts about published artefacts rather than decisions anybody makes — and
 * because a digest transcribed by a person is one nobody can re-derive, while a
 * digest transcribed *wrongly* makes every download look tampered with.
 *
 * An entry missing here is a variant this build cannot verify. That is reported
 * as `unverified` rather than passed silently, and `llm.pins.test.ts` names
 * every unpinned variant explicitly so shipping one is a deliberate edit rather
 * than an oversight.
 */
export interface ModelPin {
  bytes: number
  sha256: string
}

export const MODEL_PINS: Record<string, ModelPin> = {
  'gemma-3n-e2b-q4_k_m': { bytes: 3026881888, sha256: '189d42b4303cb1078ea8d00963f437cd6d884069b7ba2ba80b38cd09585dc415' },
  'gemma-3n-e4b-q4_k_m': { bytes: 4539054208, sha256: '43b489bb77a81bda85180e7c490d40ad7f1d5c2ce654c9b05e15e104bd3c777e' },
  'gemma-3n-e4b-q8_0': { bytes: 7353292928, sha256: '80e3a8cff3f29b2d2a6f580d8aaaf9269fff767c48eacf4306294718a76eb262' }
}
