/**
 * Generated by `npm run pin-models`. Do not edit by hand.
 *
 * The true size and SHA-256 of each catalogue variant's file, at the revision
 * the catalogue names. Kept apart from the catalogue itself because these are
 * facts about published artefacts rather than decisions anybody makes — and
 * because a digest transcribed by a person is one nobody can re-derive, while a
 * digest transcribed *wrongly* makes every download look tampered with.
 *
 * An entry missing here is a variant this build cannot verify. That is reported
 * as `unverified` rather than passed silently, and `llm.pins.test.ts` names
 * every unpinned variant explicitly so shipping one is a deliberate edit rather
 * than an oversight.
 */
export interface ModelPin {
  bytes: number
  sha256: string
}

export const MODEL_PINS: Record<string, ModelPin> = {}
