/**
 * Hand-built `.fountain` text, in the shape real tools actually write —
 * not generated by `toFountain.ts`, so `fromFountain.test.ts` proves the
 * importer against an independent idea of the format rather than against
 * itself. Mirrors `docx/fixtures.ts`'s role for the OOXML importer.
 */

/** A title page, then a short scene: heading, action, a cue whose speech
 *  carries a mid-speech parenthetical, a second cue, and a transition — one
 *  of each element this build recognises, formatted the way Highland writes
 *  it (unforced scene headings and transitions, since their own prefixes
 *  already parse; a parenthetical stays on the same unbroken block as the
 *  cue it belongs to, exactly as a real tool emits it). */
export const SAMPLE_SCREENPLAY = `Title: The Long Way Home
Author: A. Writer
Draft date: 2026-01-01

INT. KITCHEN - NIGHT

Rain against the window. MARA stands at the sink, not moving.

MARA
I thought you left already.
(beat)
I heard the car.

JOEL
I came back for something.

CUT TO:

EXT. DRIVEWAY - CONTINUOUS

The car sits idling, headlights on.
`

/** A scene heading forced with a leading dot, and a transition forced with `>` — the two markers `fromFountain.ts` must strip. */
export const FORCED_MARKERS = `.CLOSE ON - THE LETTER

We read it over her shoulder.

>SMASH CUT TO BLACK.
`

/** A single all-caps action line with no dialogue underneath it — must not be mistaken for a character cue, which always needs one. */
export const CAPS_ACTION_LINE = `INT. WAREHOUSE - DAY

THE CEILING COLLAPSES.

Dust fills the room.
`

/** No title page at all: the body must still parse from the very first line. */
export const NO_TITLE_PAGE = `EXT. RIDGE - DAWN

A lone figure walks the ridge line.
`
